# Generated by Django 3.2.7 on 2021-09-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_remove_perfil_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
    ]
