# Generated by Django 3.2.7 on 2021-10-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('localidade', models.CharField(max_length=200, verbose_name='Localidade')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('data_postado', models.DateTimeField(auto_now_add=True, verbose_name='Data postado')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('avaliacao', models.SmallIntegerField(choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('likes', models.ManyToManyField(related_name='likes_viagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('opiniao', models.TextField(verbose_name='Opinião')),
                ('foto', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, size=[640, 360], upload_to='pontos_turisticos/')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_turistico_viagem', to='viagens.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_comentario', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_viagem', to='viagens.viagem')),
            ],
        ),
    ]
