# Generated by Django 3.2.7 on 2021-10-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_viagem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='pais',
        ),
    ]
