# Generated by Django 3.2.7 on 2021-10-06 14:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_remove_viagem_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='foto',
            field=django_resized.forms.ResizedImageField(crop=None, default='viagens/default_viagem.jpg', force_format=None, keep_meta=True, quality=80, size=[640, 360], upload_to='viagens/'),
            preserve_default=False,
        ),
    ]
