# Generated by Django 3.2.7 on 2021-10-06 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_viagem_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='Comentário'),
        ),
    ]
