# Generated by Django 3.2.7 on 2021-10-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_auto_20211006_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='datahora',
            new_name='data_hora',
        ),
    ]
